### ISSUE TITLE
http dependency breaks on Apple M1

### ISSUE THREAD

**Issue by mdolon** [excid3/noticed#82] opened 2021-01-05 22:59 UTC
I kept getting the following error when trying to run my Rails app that uses Jumpstart Pro:
```
Could not open library '/Users/---/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/http-parser-1.2.2/ext/aarch64-darwin/libhttp-parser-ext.bundle': dlopen(/Users/---/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/http-parser-1.2.2/ext/aarch64-darwin/libhttp-parser-ext.bundle, 5): no suitable image found.  Did find: (LoadError)
	/Users/---/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/http-parser-1.2.2/ext/aarch64-darwin/libhttp-parser-ext.bundle: mach-o, but wrong architecture
	/Users/---/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/http-parser-1.2.2/ext/aarch64-darwin/libhttp-parser-ext.bundle: stat() failed with errno=25
```

I was able to narrow do the problematic gem to `noticed` -- turns out the `http` dependency is not yet M1 compatible.

**Comment by excid3** [comment] 2021-01-06 01:39
Hey @mdolon this is a duplicate of #81. The bug is with the http-parser gem, not noticed. I'm keeping an eye on their gem and they just merged in a change that should fix it. We need them to release a new version in the meantime though.

If it takes too long, I may replace http.rb with something else. I'll leave this issue open until it's resolved.

**Comment by excid3** [comment] 2021-03-13 04:19
http-parser 1.2.3 was released, so that should fix this. Feel free to reopen if not. I don't have an M1 to test with.

**Closed by excid3** 2021-03-13 04:19 UTC
Labels: dependencies, duplicate
